=== harisbarki/CS3716-volley-tourney/Source_code/tournaments/tournament.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT tournament (name,type,numTeams,regStartDate,regEndDate,startDate,endDate,minPlayerAge,maxPlayerAge)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT numTeams (#PCDATA)>
<!ELEMENT regStartDate (#PCDATA)>
<!ELEMENT regEndDate (#PCDATA)>
<!ELEMENT startDate (#PCDATA)>
<!ELEMENT endDate (#PCDATA)>
<!ELEMENT minPlayerAge (#PCDATA)>
<!ELEMENT maxPLayerAge (#PCDATA)>
<!ELEMENT teamList (team)>
<!ELEMENT team (player,age)>
<!ELEMENT player (name,age)>
<!ELEMENT age (#PCDATA)>

=== harisbarki/CS3716-volley-tourney/Source_code/tournaments/tourney2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE tournament SYSTEM "tournament.dtd">
<tournament>
    <name>tourney2</name>
    <type>Single Elimination</type>
    <numTeams>12</numTeams>
    <regStartDate>2016-11-15</regStartDate>
    <regEndDate>2016-11-18</regEndDate>
    <startDate>2016-11-22</startDate>
    <endDate>2016-11-22</endDate>
    <minPlayerAge>14</minPlayerAge>
    <maxPlayerAge>24</maxPlayerAge>
</tournament>

=== harisbarki/CS3716-volley-tourney/Source_code/tournaments/Tomi's tourney.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE tournament SYSTEM "tournament.dtd">
<tournament>
    <id>2</id>
    <name>Tomi's tourney</name>
    <type>Divisions</type>
    <numTeams>7</numTeams>
    <regStartDate>2016-11-01</regStartDate>
    <regEndDate>2016-11-06</regEndDate>
    <startDate>2016-12-08</startDate>
    <endDate>2016-12-08</endDate>
    <minPlayerAge>15</minPlayerAge>
    <maxPlayerAge>30</maxPlayerAge>
    <teamList>
        <team>
            <teamName>demo 2</teamName>
            <player>
                <name>dfghdfgh</name>
                <age>15</age>
            </player>
            <player>
                <name>gwrgbsr</name>
                <age>16</age>
            </player>
            <player>
                <name>bsfb</name>
                <age>15</age>
            </player>
            <player>
                <name>sfdbsfdb</name>
                <age>15</age>
            </player>
            <player>
                <name>s</name>
                <age>15</age>
            </player>
            <player>
                <name>sfbsfgbsgb</name>
                <age>15</age>
            </player>
        </team>
        <team>
            <teamName>demo 3</teamName>
            <player>
                <name>dfghdfgh</name>
                <age>15</age>
            </player>
            <player>
                <name>gwrgbsr</name>
                <age>16</age>
            </player>
            <player>
                <name>bsfb</name>
                <age>15</age>
            </player>
            <player>
                <name>sfdbsfdb</name>
                <age>15</age>
            </player>
            <player>
                <name>s</name>
                <age>15</age>
            </player>
            <player>
                <name>sfbsfgbsgb</name>
                <age>15</age>
            </player>
        </team>
        <team>
            <teamName>demo 4</teamName>
            <player>
                <name>dfghdfgh</name>
                <age>15</age>
            </player>
            <player>
                <name>gwrgbsr</name>
                <age>16</age>
            </player>
            <player>
                <name>bsfb</name>
                <age>15</age>
            </player>
            <player>
                <name>sfdbsfdb</name>
                <age>15</age>
            </player>
            <player>
                <name>s</name>
                <age>15</age>
            </player>
            <player>
                <name>sfbsfgbsgb</name>
                <age>15</age>
            </player>
        </team>
        <team>
            <teamName>demo 5</teamName>
            <player>
                <name>dfghdfgh</name>
                <age>15</age>
            </player>
            <player>
                <name>gwrgbsr</name>
                <age>16</age>
            </player>
            <player>
                <name>bsfb</name>
                <age>15</age>
            </player>
            <player>
                <name>sfdbsfdb</name>
                <age>15</age>
            </player>
            <player>
                <name>s</name>
                <age>15</age>
            </player>
            <player>
                <name>sfbsfgbsgb</name>
                <age>15</age>
            </player>
        </team>
    <team>
            <teamName>demo 6</teamName>
            <player>
                <name>sfhsfgb</name>
                <age>15</age>
            </player>
            <player>
                <name>sfnsb</name>
                <age>15</age>
            </player>
            <player>
                <name>sgnsgn</name>
                <age>15</age>
            </player>
            <player>
                <name>fndf</name>
                <age>15</age>
            </player>
            <player>
                <name>sfgfgb</name>
                <age>15</age>
            </player>
            <player>
                <name>sfgsfgb</name>
                <age>15</age>
            </player>
        </team>
    <team>
            <teamName>demo 7s</teamName>
            <player>
                <name>gbsfgbsf</name>
                <age>15</age>
            </player>
            <player>
                <name>sfbsfb</name>
                <age>15</age>
            </player>
            <player>
                <name>sgfbb</name>
                <age>15</age>
            </player>
            <player>
                <name>sgsfgb</name>
                <age>15</age>
            </player>
            <player>
                <name>sgbsfgb</name>
                <age>15</age>
            </player>
            <player>
                <name>sgbsfgbgfb</name>
                <age>15</age>
            </player>
            <player>
                <name>sgbshrnhmg</name>
                <age>15</age>
            </player>
        </team>
    <team>
            <teamName>dgdfgbd</teamName>
            <player>
                <name>ndgbndgh</name>
                <age>15</age>
            </player>
            <player>
                <name>hdgnd</name>
                <age>15</age>
            </player>
            <player>
                <name>fhjm</name>
                <age>15</age>
            </player>
            <player>
                <name>fhjmfy</name>
                <age>15</age>
            </player>
            <player>
                <name>fjfh</name>
                <age>15</age>
            </player>
            <player>
                <name>fhmfhjm</name>
                <age>15</age>
            </player>
        </team>
    </teamList>
</tournament>

=== harisbarki/CS3716-volley-tourney/Source_code/tournaments/Dido's Tournament.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE tournament SYSTEM "tournament.dtd">
<tournament>
    <id>1</id>
    <name>Dido's Tournament</name>
    <type>Single Elimination</type>
    <numTeams>6</numTeams>
    <regStartDate>2016-12-01</regStartDate>
    <regEndDate>2016-12-02</regEndDate>
    <startDate>2016-12-03</startDate>
    <endDate>2016-12-03</endDate>
    <minPlayerAge>10</minPlayerAge>
    <maxPlayerAge>20</maxPlayerAge>
    <teamList>
        <team>
            <teamName>Team 1</teamName>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
        </team>
    <team>
            <teamName>Team 2</teamName>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
        </team>
    <team>
            <teamName>Team 3</teamName>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
        </team>
    <team>
            <teamName>Team 4</teamName>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
        </team>
    <team>
            <teamName>Team 5</teamName>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
            <player>
                <name>Dido</name>
                <age>10</age>
            </player>
        </team>
    <team>
            <teamName>hdgndg</teamName>
            <player>
                <name>dyhdng</name>
                <age>10</age>
            </player>
            <player>
                <name>dndtn</name>
                <age>10</age>
            </player>
            <player>
                <name>tkiktuk</name>
                <age>10</age>
            </player>
            <player>
                <name>rjrtyj</name>
                <age>10</age>
            </player>
            <player>
                <name>jtyey</name>
                <age>10</age>
            </player>
            <player>
                <name>eyhet</name>
                <age>10</age>
            </player>
        </team>
    </teamList>
</tournament>

=== harisbarki/CS3716-volley-tourney/Source_code/tournaments/1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE tournament SYSTEM "tournament.dtd">
<tournament>
    <id>1</id>
    <name>Test Tourney demo</name>
    <type>Divisions</type>
    <numTeams>6</numTeams>
    <regStartDate>2016-12-01</regStartDate>
    <regEndDate>2016-12-03</regEndDate>
    <startDate>2016-12-06</startDate>
    <endDate>2016-12-09</endDate>
    <minPlayerAge>10</minPlayerAge>
    <maxPlayerAge>22</maxPlayerAge>
    <teamList>
        <team>
            <teamName>Team1</teamName>
            <player>
                <name>hajosfk</name>
                <age>10</age>
            </player>
            <player>
                <name>asdadsasd</name>
                <age>10</age>
            </player>
            <player>
                <name>vddfdf</name>
                <age>10</age>
            </player>
            <player>
                <name>sdaasd</name>
                <age>10</age>
            </player>
            <player>
                <name>das</name>
                <age>10</age>
            </player>
            <player>
                <name>sadsda</name>
                <age>10</age>
            </player>
        </team>
    <team>
            <teamName>testTeam1</teamName>
            <player>
                <name>boy</name>
                <age>10</age>
            </player>
            <player>
                <name>dude</name>
                <age>10</age>
            </player>
            <player>
                <name>suh</name>
                <age>10</age>
            </player>
            <player>
                <name>fam</name>
                <age>10</age>
            </player>
            <player>
                <name>lit</name>
                <age>10</age>
            </player>
            <player>
                <name>brooo</name>
                <age>10</age>
            </player>
        </team>
    <team>
            <teamName>testTeam2</teamName>
            <player>
                <name>boy</name>
                <age>10</age>
            </player>
            <player>
                <name>dude</name>
                <age>10</age>
            </player>
            <player>
                <name>suh</name>
                <age>10</age>
            </player>
            <player>
                <name>fam</name>
                <age>10</age>
            </player>
            <player>
                <name>lit</name>
                <age>10</age>
            </player>
            <player>
                <name>brooo</name>
                <age>10</age>
            </player>
            <player>
                <name>nice</name>
                <age>10</age>
            </player>
            <player>
                <name>boy</name>
                <age>10</age>
            </player>
            <player>
                <name>play</name>
                <age>10</age>
            </player>
            <player>
                <name>google</name>
                <age>10</age>
            </player>
            <player>
                <name>apple</name>
                <age>10</age>
            </player>
            <player>
                <name>ai</name>
                <age>10</age>
            </player>
        </team>
    <team>
            <teamName>teamnew</teamName>
            <player>
                <name>kgfhg</name>
                <age>10</age>
            </player>
            <player>
                <name>kjhkjh</name>
                <age>10</age>
            </player>
            <player>
                <name>hbkjhbj</name>
                <age>10</age>
            </player>
            <player>
                <name>kjhvkhg</name>
                <age>10</age>
            </player>
            <player>
                <name>gdufytfg</name>
                <age>10</age>
            </player>
            <player>
                <name>luygugv</name>
                <age>10</age>
            </player>
        </team>
    <team>
            <teamName>demo team1</teamName>
            <player>
                <name>gsghs</name>
                <age>10</age>
            </player>
            <player>
                <name>dghjduj</name>
                <age>10</age>
            </player>
            <player>
                <name>ujeryujy</name>
                <age>10</age>
            </player>
            <player>
                <name>dhd</name>
                <age>10</age>
            </player>
            <player>
                <name>uetuyety</name>
                <age>10</age>
            </player>
            <player>
                <name>tdyjdth</name>
                <age>10</age>
            </player>
            <player>
                <name>rtjrtj</name>
                <age>10</age>
            </player>
        </team>
    <team>
            <teamName>demo team 2</teamName>
            <player>
                <name>sghdjhdt</name>
                <age>10</age>
            </player>
            <player>
                <name>etyuu</name>
                <age>10</age>
            </player>
            <player>
                <name>ryukruk</name>
                <age>10</age>
            </player>
            <player>
                <name>ryukru</name>
                <age>10</age>
            </player>
            <player>
                <name>totiotu</name>
                <age>10</age>
            </player>
            <player>
                <name>yktktuik</name>
                <age>10</age>
            </player>
        </team>
    </teamList>
</tournament>

=== harisbarki/CS3716-volley-tourney/Source_code/tournaments/tourney.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE tournament SYSTEM "tournament.dtd">
<tournament>
    <name>tourney</name>
    <type>Divisions</type>
    <numTeams>7</numTeams>
    <regStartDate>2016-11-01</regStartDate>
    <regEndDate>2016-11-03</regEndDate>
    <startDate>2016-11-07</startDate>
    <endDate>2016-11-07</endDate>
    <minPlayerAge>13</minPlayerAge>
    <maxPlayerAge>23</maxPlayerAge>
</tournament>
